{
    'name': 'Okul Aile Birliği Yönetimi',
    'version': '18.0.1.0.0',
    'summary': 'Okul Aile Birliği süreç yönetimi',
    'description': 'Türkiye okulları için Okul Aile Birliği yönetim modülü.',
    'category': 'Education',
    'license': 'LGPL-3',
    'author': 'Coflow Teknoloji',
    'website': 'https://coflow.com.tr',
    'live_test_url': 'https://coflow.com.tr',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'views/spa_school_views.xml',
        'views/spa_governance_views.xml',
        'views/spa_meeting_views.xml',
        'views/spa_finance_views.xml',
        'views/spa_operational_views.xml',
        'views/spa_menus.xml',
        'report/spa_reports.xml',
        'report/spa_report_templates.xml',
    ],
    'installable': True,
    'application': True,
}
